### ISSUE TITLE
No need for `iterator` in requirements

### ISSUE THREAD

**Issue by zsunberg** [dominikstrb/PointBasedValueIteration.jl#2]
In the requirements, there is no need for `iterator` any more. Also a heads up: in POMDPs v0.9 requirements are being moved out of POMDPs.jl and into POMDPLinter.jl

**Comment by dominikstrb** [comment]
Solved in [e1f4a8e](https://github.com/dominikstrb/PointBasedValueIteration.jl/commit/e1f4a8e1b5b927296d49ba3db8547328dbf0131b)
